// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRF8ybnwi6aFkK82aHNXEo1rXf85bg38U',
    appId: '1:146412174490:web:93b2cdd4831b398898f323',
    messagingSenderId: '146412174490',
    projectId: 'termometer-4b9d6',
    authDomain: 'termometer-4b9d6.firebaseapp.com',
    databaseURL: 'https://termometer-4b9d6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'termometer-4b9d6.firebasestorage.app',
    measurementId: 'G-95C743TLS5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRF8ybnwi6aFkK82aHNXEo1rXf85bg38U',
    appId: '1:146412174490:web:d5685d9189968e2f98f323',
    messagingSenderId: '146412174490',
    projectId: 'termometer-4b9d6',
    authDomain: 'termometer-4b9d6.firebaseapp.com',
    databaseURL: 'https://termometer-4b9d6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'termometer-4b9d6.firebasestorage.app',
    measurementId: 'G-SQ2C2QLHJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFLngH8pAqR3-wEeuUHB85yj3eNSTyY84',
    appId: '1:146412174490:android:b54e67e59a4c20d498f323',
    messagingSenderId: '146412174490',
    projectId: 'termometer-4b9d6',
    databaseURL: 'https://termometer-4b9d6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'termometer-4b9d6.firebasestorage.app',
  );

}